# DATABASE URL
spring.datasource.url=jdbc:mysql://localhost:3306/dashboard
spring.datasource.username=dashboard
spring.datasource.password=dashboard

# DATABASE DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.open-in-view=false

spring.jpa.generate-ddl=true

# Show query
spring.jpa.show-sql=true

# DDL MODE: create at firstr
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.

# CACHING
spring.cache.type=NONE

# DEV TOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.cache.period=0

spring.web.resources.static-locations=file:src/main/resources/static/

