# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mariadb://localhost:3306/dashboard
spring.datasource.username=dashboard
spring.datasource.password=dashboard

# JPA / HIBERNATE
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# CACHING
spring.cache.type=NONE

# DEV TOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.cache.period=0

spring.web.resources.static-locations=file:src/main/resources/static/

